Improvements
SartiMau/StockAppTandilAndroid pull request #24
Opened 2022-02-16 13:40 UTC by juani-lastra

- [x] After accepting permissions for the camera, load the camera.

- [x] Delete Location Object

- [x] Empty state for search list activity

- [x] Loader for search dialog

- [x] unit test use case get location

- Empty State
![ezgif-1-bba7210244](https://user-images.githubusercontent.com/96496857/154272578-d19bc601-153a-4cf6-bb94-f522cb00a528.gif)

- Camera Loading after request permissions
![ezgif-1-d25a026ed1](https://user-images.githubusercontent.com/96496857/154273032-8a2ecd5b-7f7b-42f8-a8c7-d5682963b83b.gif)

- Loader on search dialog
![ezgif-1-625eabfb15](https://user-images.githubusercontent.com/96496857/154276217-a63481ad-54bc-432f-8bda-e3f89edae1ad.gif)

2022-02-16 14:38 UTC, mauroLonghi commented on app/src/main/res/layout/activity_search_asset_list.xml
> +        android:visibility="gone"
maybe you could create a style for this text properties

2022-02-16 14:40 UTC, SartiMau requested changes

2022-02-16 14:40 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/ScannerActivity.kt
> +        this.recreate()
What is this for?

2022-02-16 14:49 UTC, juani-lastra commented on app/src/main/java/com/mobiletandil/stockapp/activity/ScannerActivity.kt
> +        this.recreate()
When is your first time on the app, to open the camera it would be requesting permissions, so before this changes, when the permissions were accepted the camera was not showing, now with this change the camera is shown after accepting the permissions, if not the app will be requesting permissions until the user accept it

2022-02-16 18:56 UTC, juani-lastra commented on app/src/main/res/layout/activity_search_asset_list.xml
> +        android:visibility="gone"
done

2022-02-17 19:02 UTC, SartiMau requested changes

2022-02-17 19:02 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/ScannerActivity.kt
> +            this.onBackPressed()
I think that this is not necessary because if the user does not accept the permissions he still will be able to use the manually version

2022-02-18 13:58 UTC, juani-lastra commented on app/src/main/java/com/mobiletandil/stockapp/activity/ScannerActivity.kt
> +            this.onBackPressed()
done

2022-02-18 15:40 UTC, mauroLonghi approved these changes

2022-02-18 17:57 UTC, SartiMau approved these changes

2022-02-18 18:07 UTC, merged