Improvements
SartiMau/StockAppTandilAndroid pull request #25
Opened 2022-02-16 16:00 UTC by Georgina-Fernandez

Improvements & fixes from previous sprints:

- [x] Include userName suffix label on Search mannually dialog Value field 

<img width="155" alt="suffix" src="https://user-images.githubusercontent.com/85899662/154300915-df5717ba-d1ae-4bd8-b0fd-75a1ef590319.PNG">

- [x] For location dropdown/spinner, if user doesn't set a value, set default value "Other"

- [x] In update form, location from DB loaded, with the dropdown/spinner ready

<img width="198" alt="location" src="https://user-images.githubusercontent.com/85899662/154301473-41b474d6-a19c-4084-baa4-4d086b50e0f2.PNG">

- [x] Successfully save in dialog instead of a toast

<img width="201" alt="save" src="https://user-images.githubusercontent.com/85899662/154301733-97ae389e-f7ec-4c2c-899d-7d2949eb2625.PNG">

- [x] Save asset with empty user mail without "@globant.com"

<img width="267" alt="DB" src="https://user-images.githubusercontent.com/85899662/154302142-8f56bca6-8a45-4dc3-b9a2-b30f4a686ea4.PNG">

- [x] Include validations on search manually Dialog, invalid mail validation

![Pixel 3a Improvements](https://user-images.githubusercontent.com/85899662/154305286-b1b4998f-733e-4a0b-ba45-11955cde862e.gif)

2022-02-16 16:37 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +                    null,
That's right. I'm deleting this two lines.

2022-02-16 17:15 UTC, SartiMau requested changes

2022-02-16 17:15 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +    private fun emptyListResponseState() {
as this method has only one line, please remove it and just put that line in the EMPTY_RESPONSE_LIST state

2022-02-16 17:15 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +        startActivity(Intent(this, MainActivity::class.java))
I think that this is not fine, you should let the user go back to the scan screen

2022-02-16 17:15 UTC, SartiMau commented on app/src/test/java/com/mobiletandil/stockapp/usecase/GetLocationUseCaseTest.kt
> +/*
do not push commented code pls. If it is not necessary anymore just delete it pls

2022-02-17 12:18 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +    private fun emptyListResponseState() {
Done

2022-02-17 12:19 UTC, Georgina-Fernandez commented on app/src/test/java/com/mobiletandil/stockapp/usecase/GetLocationUseCaseTest.kt
> +/*
Done

2022-02-17 18:45 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +        startActivity(Intent(this, MainActivity::class.java))
Done

2022-02-17 19:42 UTC, mariano98montero requested changes

2022-02-17 19:42 UTC, mariano98montero commented on app/src/test/java/com/mobiletandil/stockapp/usecase/GetLocationUseCaseTest.kt
> +        TODO()
please do not push TODO´s

2022-02-17 20:05 UTC, Georgina-Fernandez commented on app/src/test/java/com/mobiletandil/stockapp/usecase/GetLocationUseCaseTest.kt
> +        TODO()
I've already made this test . They are included now on this PR (commit 14)

2022-02-17 20:07 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +        startActivity(Intent(this, MainActivity::class.java))
this still here

2022-02-17 20:11 UTC, SartiMau requested changes

2022-02-17 20:11 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +            { this.onReturnToMainPressed() },
this should call the viewmodel and do this action from a state, not directly. In this way you are not using the MVVM pattern

2022-02-17 20:11 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +    fun onReturnToMainPressed() {
after the previous comment, I think that this method should be unnecessary

2022-02-18 17:53 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +        startActivity(Intent(this, MainActivity::class.java))
Sorry,  I've already changed this function and let the user to return to scan screen. But this has already been changed in Juani's PR (that is not merged yet) without this dialog

2022-02-18 17:53 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +    fun onReturnToMainPressed() {
Done

2022-02-21 18:25 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +            { this.onReturnToScannerActivityPressed() },
Done

2022-02-21 18:26 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +                    { startActivity(Intent(this, MainActivity::class.java)) },
Done

2022-02-21 19:54 UTC, SartiMau requested changes

2022-02-21 19:54 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +    private fun initMainActivity() {
this method is unnecessary, please remove it

2022-02-21 19:54 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
>                      { eventData.asset?.let { this.setAssetUpdateFormFields(it) } },
this should call the viewmodel

2022-02-21 19:54 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +        private const val EMPTY_STRING = ""
Please remove this constant and use the Constants.EMPTY_STRING one

2022-02-21 19:54 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +    private fun onReturnToScannerActivityPressed() {
this method is nos necessary, please remove it and call the ViewModel directly

2022-02-22 15:37 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +    private fun onReturnToScannerActivityPressed() {
Done

2022-02-22 15:38 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +        private const val EMPTY_STRING = ""
Done

2022-02-22 15:46 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
>                      { eventData.asset?.let { this.setAssetUpdateFormFields(it) } },
Done

2022-02-22 20:27 UTC, mauroLonghi approved these changes

2022-02-22 20:28 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +                startActivity(ScannerActivity.getIntent(this, ScannerActivity.RedirectionOrder.TAG_SEARCH_ASSET_REDIRECTION))
this shouldn't be onBackPressed? instead of start a new activity

2022-02-22 20:50 UTC, Georgina-Fernandez commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetInformationListActivity.kt
> +                startActivity(ScannerActivity.getIntent(this, ScannerActivity.RedirectionOrder.TAG_SEARCH_ASSET_REDIRECTION))
Yes, done

2022-02-22 20:52 UTC, SartiMau approved these changes

2022-02-23 12:16 UTC, merged