comments from merge to main
SartiMau/StockAppTandilAndroid pull request #28
Opened 2022-02-21 15:53 UTC by juani-lastra

- [ ] Eliminar el override fun onBackPressed() del form

- [ ] please change the name "Arroba" to "AT"
 
- [ ] What happens if location comes with CoroutineResult.Failure?
 
- [ ] Styles linea 55: do not hardcode pls, use dimens
 
- [ ] Styles lines 125, 63,51,52,11,12,119,133: Do not put hints in styles as they are specific for each field. Add the hint in the view and remove this style
 
- [ ] Search picker linea 98: please use representative names for this let{}

2022-02-21 20:21 UTC, mauroLonghi commented on app/src/test/java/com/mobiletandil/stockapp/viewmodel/AssetFormViewModelTest.kt
> +            TEST_BARCODE, liveData.observedValues[1]?.peekContent()?.barcode
you have here and bellow severals hardcodes , pls remove

2022-02-21 20:37 UTC, juani-lastra commented on app/src/test/java/com/mobiletandil/stockapp/viewmodel/AssetFormViewModelTest.kt
> +            TEST_BARCODE, liveData.observedValues[1]?.peekContent()?.barcode
Done

2022-02-22 12:26 UTC, mauroLonghi approved these changes

2022-02-22 12:43 UTC, SartiMau requested changes

2022-02-22 12:43 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +                    { startActivity(Intent(this, MainActivity::class.java)) },
this should calll the viewmodel, there set an state and the activity react to that event with this startActivity

2022-02-22 12:43 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/ScannerActivity.kt
> +                        { startActivity(Intent(this, MainActivity::class.java)) },
this should calll the viewmodel, there set an state and the activity react to that event with this startActivity

2022-02-22 12:43 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/fragment/SearchPickerFragment.kt
> +                        { startActivity(Intent(requireContext(), MainActivity::class.java)) },
this should calll the viewmodel, there set an state and the fragment react to that event with this startActivity

2022-02-22 12:43 UTC, SartiMau commented on app/src/test/java/com/mobiletandil/stockapp/viewmodel/AssetFormViewModelTest.kt
> +            successSaveList[FIRST_VALUE].state,
I think the the constants FIRST_VALUE and SECOND_VALUE are not necessary, to grants readability

2022-02-22 12:54 UTC, juani-lastra commented on app/src/test/java/com/mobiletandil/stockapp/viewmodel/AssetFormViewModelTest.kt
> +            successSaveList[FIRST_VALUE].state,
@mauroLonghi request that

2022-02-22 13:23 UTC, juani-lastra commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +                    { startActivity(Intent(this, MainActivity::class.java)) },
Done

2022-02-22 13:23 UTC, juani-lastra commented on app/src/main/java/com/mobiletandil/stockapp/activity/ScannerActivity.kt
> +                        { startActivity(Intent(this, MainActivity::class.java)) },
Done

2022-02-22 13:23 UTC, juani-lastra commented on app/src/main/java/com/mobiletandil/stockapp/fragment/SearchPickerFragment.kt
> +                        { startActivity(Intent(requireContext(), MainActivity::class.java)) },
Done

2022-02-22 13:28 UTC, SartiMau approved these changes

2022-02-22 13:29 UTC, mauroLonghi commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +            AssetFormState.GO_TO_MAIN_ACTIVITY -> startActivity(Intent(this, MainActivity::class.java))
the same comment as mau, you need to call assetViewModel.goToMainActivity() here, its the same case

2022-02-22 13:31 UTC, juani-lastra commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +            AssetFormState.GO_TO_MAIN_ACTIVITY -> startActivity(Intent(this, MainActivity::class.java))
this is the state that comes from viewmodel

2022-02-22 13:35 UTC, merged