Internet validation improvements
SartiMau/StockAppTandilAndroid pull request #29
Opened 2022-02-21 17:06 UTC by ignaciocervinoGlob

### Description
Fixing internet connection validations.

### Tasks
#### Camera:
- [x] If user enters to the camera and has no internet connection, the dialog returns to main

#### Add form:
- [x] If the user enter to the add form without connection, the dialog returns to main
- [x] If a user lose connection while interacting with the add form, the magnifying glass icon and save button show an alert that keeps the user in the same form, so he can solve the internet issue there and continue when he has internet.

#### Update form:
- [x] If user enters to the update form without internet, the internet dialog return him to the asset list results.
- [x] Same validation as add form

#### Search dialog:
- [x] If user selects location filter without internet, it shows immediately an internet dialog that dismiss the alert
- [x] If user press search button and there is no internet, the dialog return him to the camera or assets list.

### Evidences
#### Alert dialog
| Add manually button | Save button |
|---------------|-------------|
| ![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/90403672/154998593-82f3d08d-f9d6-4ddd-88d1-ff97c4cc436f.gif) | ![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/90403672/154998804-2e2f48de-50e2-4f3e-ad8c-ec58ab17ccef.gif) |

| No internet magnifying glass  | Update form |
|---------------|-------------|
| ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/90403672/154999093-a25d9a90-6812-496d-9e8c-d5a8b6b6f050.gif) | ![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/90403672/154999245-1bce7b3a-0a72-4214-9f00-d7391ae06a30.gif) |  

| Location filter  | Search button |
|---------------|-------------|
| ![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/90403672/154999540-cf77abea-c03b-4d97-9656-d929777a2203.gif) | https://user-images.githubusercontent.com/90403672/154999708-15076c47-67dd-474f-ae35-8d2847952382.mp4 |

2022-02-21 17:38 UTC, SartiMau requested changes

2022-02-21 17:38 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +                    { this.onBackPressed() }
this should call the viewmodel and from the ViewModel set a state and the activity react to that change calling the onBackPressed()

2022-02-21 17:38 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +                    { finish() }
this should call the viewmodel and from the ViewModel set a state and the activity react to that change calling the finish()

2022-02-21 17:38 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/fragment/SearchPickerFragment.kt
> +                        context?.let { context ->
please try to put all this let statement into a one-line for more readability

2022-02-21 18:32 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +                    { this.onBackPressed() }
done

2022-02-21 18:32 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobiletandil/stockapp/activity/AssetFormActivity.kt
> +                    { finish() }
done

2022-02-21 18:32 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobiletandil/stockapp/fragment/SearchPickerFragment.kt
> +                        context?.let { context ->
done

2022-02-21 19:22 UTC, SartiMau approved these changes

2022-02-22 12:44 UTC, mauroLonghi approved these changes

2022-02-22 13:05 UTC, merged