Fix barcode scanner issues + scroll edit text
SartiMau/StockAppTandilAndroid pull request #30
Opened 2022-02-23 18:20 UTC by ignaciocervinoGlob

2022-02-24 12:54 UTC, SartiMau requested changes

2022-02-24 12:54 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/viewModel/AssetFormViewModel.kt
> +        SET_ASSET_UPDATE_FORM,
remove this extra comma

2022-02-24 12:54 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/activity/ScannerActivity.kt
> +                        { startActivity(AssetFormActivity.newIntent(this, eventData.value, true, eventData.asset)) },
check this please, remember that from here you should call the viewModel. Check it in all this class

2022-02-24 13:25 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobiletandil/stockapp/viewModel/AssetFormViewModel.kt
> +        SET_ASSET_UPDATE_FORM,
done

2022-02-24 15:18 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobiletandil/stockapp/activity/ScannerActivity.kt
> +                        { startActivity(AssetFormActivity.newIntent(this, eventData.value, true, eventData.asset)) },
done

2022-02-24 19:23 UTC, SartiMau requested changes

2022-02-24 19:23 UTC, SartiMau commented on app/src/main/java/com/mobiletandil/stockapp/viewModel/SearchPickerViewModel.kt
> +    fun getLocations() = viewModelScope.launch {
is this change okay? I remember that we fix this with @Georgina-Fernandez

2022-02-24 19:31 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobiletandil/stockapp/viewModel/SearchPickerViewModel.kt
> +    fun getLocations() = viewModelScope.launch {
It's for testing purpose, if it's private I don't find the way to test it

2022-02-25 12:56 UTC, SartiMau approved these changes

2022-02-25 12:58 UTC, GARAF004 approved these changes

2022-02-25 12:58 UTC, MarcosCGlobant approved these changes

2022-02-25 13:01 UTC, merged